[package]
name = "blue/piano-rbx"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
UILabs = "pepeeltoro41/ui-labs@2.3.8"
Fusion = "elttob/fusion@0.3.0"
Icon = "1foreverhd/topbarplus@3.4.0"
